<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="58131" started-at="2018-08-20T04:49:31Z" finished-at="2018-08-20T04:50:29Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="33930" started-at="2018-08-20T04:49:31Z" finished-at="2018-08-20T04:50:05Z">
      <class name="com.qa.sweety.tests.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="setUp" is-config="true" duration-ms="7141" started-at="2018-08-20T10:19:31Z" finished-at="2018-08-20T10:19:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="pageTitleTest()[pri:1, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="pageTitleTest" duration-ms="3028" started-at="2018-08-20T10:19:38Z" finished-at="2018-08-20T10:19:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="tearDown" is-config="true" duration-ms="101" started-at="2018-08-20T10:19:41Z" finished-at="2018-08-20T10:19:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="setUp" is-config="true" duration-ms="3365" started-at="2018-08-20T10:19:41Z" finished-at="2018-08-20T10:19:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validLoginTest()[pri:2, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="validLoginTest" duration-ms="4447" started-at="2018-08-20T10:19:45Z" finished-at="2018-08-20T10:19:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="tearDown" is-config="true" duration-ms="108" started-at="2018-08-20T10:19:49Z" finished-at="2018-08-20T10:19:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="setUp" is-config="true" duration-ms="3849" started-at="2018-08-20T10:19:49Z" finished-at="2018-08-20T10:19:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="invalidPasswordTest()[pri:3, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="invalidPasswordTest" duration-ms="4310" started-at="2018-08-20T10:19:53Z" finished-at="2018-08-20T10:19:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Signed in successfully.] but found [Invalid email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Signed in successfully.] but found [Invalid email or password.]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.qa.sweety.tests.LoginPageTest.invalidPasswordTest(LoginPageTest.java:81)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidPasswordTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="tearDown" is-config="true" duration-ms="96" started-at="2018-08-20T10:19:57Z" finished-at="2018-08-20T10:19:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="setUp" is-config="true" duration-ms="3720" started-at="2018-08-20T10:19:57Z" finished-at="2018-08-20T10:20:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="invalidEmailTest()[pri:4, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="invalidEmailTest" duration-ms="3601" started-at="2018-08-20T10:20:01Z" finished-at="2018-08-20T10:20:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Signed in successfully.] but found [You need to sign in or sign up before continuing.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Signed in successfully.] but found [You need to sign in or sign up before continuing.]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.qa.sweety.tests.LoginPageTest.invalidEmailTest(LoginPageTest.java:88)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidEmailTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.sweety.tests.LoginPageTest@13eb8acf]" name="tearDown" is-config="true" duration-ms="93" started-at="2018-08-20T10:20:05Z" finished-at="2018-08-20T10:20:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.sweety.tests.LoginPageTest -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="11423" started-at="2018-08-20T04:50:05Z" finished-at="2018-08-20T04:50:16Z">
      <class name="com.qa.sweety.tests.EntryPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.sweety.tests.EntryPageTest@67b467e9]" name="setUp" is-config="true" duration-ms="4179" started-at="2018-08-20T10:20:05Z" finished-at="2018-08-20T10:20:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyEntry()[pri:1, instance:com.qa.sweety.tests.EntryPageTest@67b467e9]" name="verifyEntry" duration-ms="7092" started-at="2018-08-20T10:20:09Z" finished-at="2018-08-20T10:20:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEntry -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.sweety.tests.EntryPageTest@67b467e9]" name="tearDown" is-config="true" duration-ms="149" started-at="2018-08-20T10:20:16Z" finished-at="2018-08-20T10:20:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.sweety.tests.EntryPageTest -->
    </test> <!-- Test2 -->
    <test name="Test3" duration-ms="12661" started-at="2018-08-20T04:50:16Z" finished-at="2018-08-20T04:50:29Z">
      <class name="com.qa.sweety.tests.ReportPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.sweety.tests.ReportPageTest@481a15ff]" name="setUp" is-config="true" duration-ms="3587" started-at="2018-08-20T10:20:16Z" finished-at="2018-08-20T10:20:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyReport()[pri:1, instance:com.qa.sweety.tests.ReportPageTest@481a15ff]" name="verifyReport" duration-ms="8917" started-at="2018-08-20T10:20:20Z" finished-at="2018-08-20T10:20:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyReport -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.sweety.tests.ReportPageTest@481a15ff]" name="tearDown" is-config="true" duration-ms="155" started-at="2018-08-20T10:20:29Z" finished-at="2018-08-20T10:20:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.sweety.tests.ReportPageTest -->
    </test> <!-- Test3 -->
  </suite> <!-- Suite -->
</testng-results>
